spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_API_CLIENT_ID}
            clientSecret: ${GITHUB_API_CLIENT_SECRET}

server:
  port: 5000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO