name: build

on:
  push:
    branches:
      - 'main'
      - 'releases/v*'
  pull_request:
    branches:
      - 'main'
      - 'releases/v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Setup Java 11 for the build
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      # Build source code using Maven
      - name: Build with Maven
        run: mvn -B package -D skipTests --file pom.xml