name: build

on:
  push:
    branches:
      - 'main'
      - 'releases/v*'
  pull_request:
    branches:
      - 'main'
      - 'releases/v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Setup Java 11 for the build
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      # Build source code using Maven
      - name: Build with Maven
        run: mvn -B package -D skipTests --file pom.xml

      # Generate Jacoco Badge
      - name: Generate Jacoco Badge
          id: jacoco
          uses: cicirello/jacoco-badge-generator@v2
          with:
            generate-coverage-badge: false
            generate-coverage-endpoint: true
            generate-branches-endpoint: true

      # Log coverage percentages
      - name: Log coverage percentage
          run: |
            echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
            echo "branches = ${{ steps.jacoco.outputs.branches }}"

      # Commit changes and push
      - name: Commit and push
          if: ${{ github.event_name != 'pull_request' }}
          run: |
            cd .github/badges
            if [[ `git status --porcelain *.json` ]]; then
              git config --global user.name 'github-actions'
              git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
              git add *.json
              git commit -m "Autogenerated JaCoCo JSON endpoints for Shields" *.json
              git push
            fi

      # Upload the coverage report
      - name: Upload Jacoco coverage report
          uses: actions/upload-artifact@v2
          with:
            name: jacoco-report
            path: target/site/jacoco/